#!/bin/bash
# Resilient wrapper around `tauri build` for the macOS DMG Spotlight race.
#
# The bug: bundle_dmg.sh (regenerated by tauri-bundler every build) creates
# a writable scratch DMG, mounts it, populates with .app + Finder cosmetics,
# then calls `hdiutil detach` to unmount before converting to the final
# read-only DMG. macOS Spotlight starts indexing the freshly-mounted volume
# in parallel and sometimes holds it past detach time — `hdiutil` returns
# "Resource busy" and the script gives up after 3 retries. Same machine,
# same script, just a race between Spotlight finishing and the script's
# eject. Confirmed on v0.3.7: failed twice in a row then succeeded on the
# third try after manual cleanup.
#
# We can't patch bundle_dmg.sh (regenerated each build). We can't easily
# inject .metadata_never_index (it'd need to be at the volume root, and
# Tauri controls the source folder layout). So we sit ABOVE the build:
# detect the Spotlight-busy signature, clean the leftover rw.*.dmg mount
# bundle_dmg.sh leaves behind on failure, retry. Real failures (cargo
# errors, frontend errors, anything OTHER than the Spotlight signature)
# fail fast — don't waste minutes retrying a real compile error.
#
# Usage matches `tauri build`: forwards all args. Successful exit mounts
# the produced DMG via `hdiutil attach` (matches the prior tauri:build
# behavior so downstream scripts/people see the same result).

set -e
cd "$(dirname "$0")/.."  # project root

MAX_TRIES=4
RETRY_DELAY=3 # seconds between attempts (let Spotlight settle)
BUNDLE_MACOS="src-tauri/target/release/bundle/macos"
BUNDLE_DMG="src-tauri/target/release/bundle/dmg"

# True if the build log shows the Spotlight-busy signature. Retrying makes
# sense for THIS failure; any other failure (cargo, frontend, signing) is
# a real error that won't be fixed by re-running. Pattern is narrow on
# purpose — over-broad matching would mask real bugs as transient.
is_spotlight_race() {
  local log="$1"
  grep -qE "couldn't unmount.*Resource busy|failed to run.*bundle_dmg.sh|The volume can't be ejected" "$log"
}

# Force-detach any rw.*.dmg mount left over from a prior bundle_dmg.sh
# failure. The scratch DMG sits open on /dev/diskN until detached; the
# next bundle_dmg.sh attempt can't proceed if a stale one is still
# attached. Plus remove the on-disk rw.*.dmg + .DS_Store so the next
# build starts from a known-clean state (matches the old tauri:build's
# `rm -f` prologue).
cleanup_stale_mounts() {
  local devs
  devs=$(hdiutil info | awk '
    /^image-path/ { p=$0 }
    /\/dev\/disk/ && p ~ /rw\..*Budget Itemizer/ { print $1 }
  ' | sort -u)
  for dev in $devs; do
    echo "  [dmg-retry] Detaching stale mount: $dev"
    hdiutil detach -force "$dev" 2>&1 | sed 's/^/    /' || true
  done
  rm -f $BUNDLE_MACOS/rw.*.dmg 2>/dev/null || true
  rm -f $BUNDLE_MACOS/.DS_Store 2>/dev/null || true
}

LOG=$(mktemp -t tauri-build.XXXXXX.log)
trap 'rm -f "$LOG"' EXIT

for attempt in $(seq 1 $MAX_TRIES); do
  echo ""
  echo "==> [dmg-retry] tauri build attempt $attempt of $MAX_TRIES"
  cleanup_stale_mounts

  # tee the output so we keep it on screen AND can grep the log
  set +e
  npx tauri build "$@" 2>&1 | tee "$LOG"
  rc=${PIPESTATUS[0]}
  set -e

  if [ "$rc" -eq 0 ]; then
    echo ""
    echo "==> [dmg-retry] tauri build succeeded on attempt $attempt"
    # Mount the produced DMG if one was actually built THIS run (matches
    # prior tauri:build behavior). Read the build log for tauri-bundler's
    # own "Bundling ... .dmg" line — robust to any --bundles invocation,
    # and avoids mounting a stale DMG left over on disk from a prior
    # release build when this run intentionally skipped the dmg target.
    if grep -qE "Bundling .*\.dmg" "$LOG"; then
      dmg=$(ls $BUNDLE_DMG/*.dmg 2>/dev/null | head -1 || true)
      if [ -n "$dmg" ]; then
        echo "==> [dmg-retry] Attaching $dmg"
        hdiutil attach "$dmg"
      fi
    fi
    exit 0
  fi

  if is_spotlight_race "$LOG"; then
    echo ""
    echo "==> [dmg-retry] Spotlight-busy race detected on attempt $attempt."
    if [ "$attempt" -lt "$MAX_TRIES" ]; then
      echo "    Cleaning up and retrying in ${RETRY_DELAY}s..."
      sleep "$RETRY_DELAY"
      continue
    fi
    echo "    Out of retries. Last build output is above."
    exit "$rc"
  fi

  # Some other failure (cargo, frontend, signing). Don't waste minutes
  # retrying a real bug — fail fast with the original exit code.
  echo ""
  echo "==> [dmg-retry] Build failed with an error other than the Spotlight race; not retrying."
  exit "$rc"
done
